### PR TITLE
Fix broken link "View All" in renature home page.

### LINKED ISSUE #55: Documentation - Broken link
Hi,

The "View All" button link is wrong.
https://github.com/FormidableLabs/renature/blob/master/docs/src/screens/home/more-oss.js#L104
line: 104

This cause the link to be: 
https://formidable.com/open-source/renature/https://formidable.com/open-source/

What it should be:
https://formidable.com/open-source/

Should probably be:
`<Button light to="open-source/">`

### PR DESCRIPTION
**Pull request by joseph-passineau**
Modified the oss content and added "link" to it.

fixes #55

### CODE REVIEW

**Comment by parkerziegler** [comment]
Looks great. It appears from the build that you might have some Prettier errors in the `docs` folder. If you `cd` into that directory you should be able to run `yarn format` to fix those, and then run `yarn check-ci` to verify it'll pass CI. Thanks!

**Comment by joseph-passineau** [comment]
So I fixed the syntax errors, but the build still fails. Seems like a timeout.

`No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.`

I would just restart a build, but I don't have access.

**Comment by ryan-roemer** [comment]
The hang is because forked PRs don’t have secret env vars. Parker you can locally verify and/or convert this to a branch PR.

Thanks for the help @joseph-passineau!

**Comment by parkerziegler** [comment]
Thanks again!

**Comment by joseph-passineau** [comment]
My pleasure and keep up the good work.  👍

**Pull request merged**
